configName: pic32cx_sg41_cult
folderName: ''
format_version: v1.0
frameworkPath: ../../../../..
processor: PIC32CX1025SG41128
projectName: ''
settings:
  PackageFilter: csp;
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  CMSISPath: .\dev_packs\arm\CMSIS\5.8.0
  MERGE_STRATEGY: USER_ALL
  DFPPath: .\dev_packs\Microchip\PIC32CX-SG41_DFP\3.1.33\atdf\PIC32CX1025SG41128.atdf
